version: "3"
services:
  spamassassin:
    image: instantlinux/spamassassin:3.4.6-1
    ports:
      - ${SPAMASSASSIN_PORT:-783}:783
    restart: always

  eml_analyzer:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - ${PORT:-8000}:8000
    environment:
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - URLSCAN_API_KEY=${URLSCAN_API_KEY}
      - INQUEST_API_KEY=${INQUEST_API_KEY}
      - SPAMASSASSIN_HOST=spamassassin
      - SPAMASSASSIN_PORT=${SPAMASSASSIN_PORT:-783}
      - REDIS_HOST=redis
    restart: always
    depends_on:
      - spamassassin
  redis:
    image: library/redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD:-changeme}"
    ports:
      - 6379:6379
