services:
  spamassassin:
    image: instantlinux/spamassassin:4.0.0-6
    platform: linux/x86_64
    ports:
      - ${SPAMASSASSIN_PORT:-793}:783
    restart: always

  redis:
    image: "redis/redis-stack:7.2.0-v8"
    restart: always
    ports:
      - ${REDIS_PORT:-6389}:6379
      - ${REDIS_INSIGHT_PORT:-8011}:8001
    volumes:
      - redis-data:/data

  eml_analyzer:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - ${PORT:-8010}:8000
    environment:
      - SPAMASSASSIN_HOST=spamassassin
      - SPAMASSASSIN_PORT=${SPAMASSASSIN_PORT:-793}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6389}
    restart: always
    depends_on:
      - spamassassin
      - redis

volumes:
  redis-data:
