[tool.poetry]
name = "eml_analyzer"
version = "0.1.0"
description = ""
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.7.0"
aiometer = "^0.3.0"
aiospamc = "^0.7.1"
arrow = "^1.2.0"
async-timeout = "^3.0.1"
beautifulsoup4 = "^4.10.0"
compoundfiles = "^0.3"
compressed-rtf = "^1.0.6"
dateparser = "^1.1.0"
eml_parser = {extras = ["filemagic"], version = "1.15.0"}
fastapi = "^0.70.0"
fastapi-utils = "^0.2.1"
gunicorn = "^20.1.0"
html2text = "^2020.1.16"
httpx = "^0.20.0"
ioc-finder = "^6.0.1"
loguru = "^0.5.3"
oletools = "0.55.1"
pydantic = "^1.8.2"
python-multipart = "^0.0.5"
uvicorn = "^0.15.0"
vt-py = "^0.7.5"

[tool.poetry.dev-dependencies]
aioresponses = "^0.7.2"
asynctest = "^0.13.0"
autoflake = "^1.4"
autopep8 = "^1.5.7"
black = "^21.9b0"
coveralls = "^3.2.0"
flake8 = "^3.9.2"
isort = "^5.9.3"
mypy = "^0.910"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"
pytest-cov = "^3.0.0"
pytest-env = "^0.6.2"
pytest-mock = "^3.6.1"
pytest-parallel = "^0.1.1"
pytest-randomly = "^3.10.1"
pytest-sugar = "^0.9.4"
pytest-timeout = "^2.0.1"
pyupgrade = "^2.29.0"
respx = "^0.18.0"
vcrpy = "^4.1.1"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["aiometer", "aioresponses", "aiospamc", "arrow", "async_timeout", "asynctest", "bs4", "compoundfiles", "compressed_rtf", "dateparser", "eml_parser", "fastapi", "fastapi_utils", "html2text", "httpx", "ioc_finder", "loguru", "magic", "olefile", "oletools", "pydantic", "pytest", "pytest_mock", "respx", "starlette", "vcr", "vt"]
line_length = 88
multi_line_output = 3
use_parentheses= true

[tool.pytest.ini_options]
minversion = "6.0"
env = ["VIRUSTOTAL_API_KEY=foo", "INQUEST_API_KEY=bar", "TESTING=True"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
